#!/usr/bin/env bash

set -e

files=("$@")

if [ ${#files[@]} -eq 0 ]; then
    read -rp "Enter file(s) to sort: " -a files
fi

if [ ${#files[@]} -eq 0 ]; then
    echo "No files provided."
    exit 1
fi

for file in "${files[@]}"; do
    if [ ! -f "$file" ]; then
        echo "Error: '$file' is not a file."
        exit 1
    fi

    sort "$file" -o "$file"
done

# Hang

KEEP_OPEN=true

if [ "$KEEP_OPEN" = true ]; then
    echo
    read -p "Press 'Enter' to exit / Type 'disable' to disable hanging: " response
    if [ "$response" = "disable" ]; then
        sed -i 's/^KEEP_OPEN=true/KEEP_OPEN=false/' "$0"
        echo
        echo "KEEP_OPEN set to false"
        echo "Change 'KEEP_OPEN=true' to enable"
        sleep 4
    fi
fi
