#!/usr/bin/env bash

set -e

for d in */; do
    if [ -d "$d/.git" ]; then
        echo "Pulling $d..."
        git -C "$d" pull &
    fi
done

wait

# Just delete this line if you don't want it
read -p "Press enter to exit..."
