#!/usr/bin/env bash

set -e

for d in */; do
    if [ -d "$d/.git" ]; then
        echo "Pushing $d..."
        (
            git -C "$d" add .
            git -C "$d" commit -m "auto-commit" || true
            git -C "$d" push
        ) &
    fi
done

wait

# Just delete this line if you don't want it
read -p "Press enter to exit..."
