#!/usr/bin/env bash

set -e

echo

read -rp "    Author of Target    :   " author
[ -z "$author" ] && { echo "No username entered. Exiting."; exit 1; }

read -rp "    Name of Target      :   " repo
[ -z "$repo" ] && { echo "No repository name entered. Exiting."; exit 1; }

read -rp "    ssh/HTTPS           :   " method
method=$(echo "$method" | tr '[:upper:]' '[:lower:]')

if [[ "$method" == "ssh" ]]; then
    clone_url="git@github.com:$author/$repo.git"
    method="ssh"
else
    clone_url="https://github.com/$author/$repo.git"
    method="https"
fi

if [ -d "$repo/.git" ]; then
    echo
    echo "Repository '$repo' already exists."
    echo
    exit 0
fi

echo
echo "Cloning $author/$repo using $method..."
if git clone "$clone_url" >/dev/null 2>&1; then
    echo
    echo "Clone of "$author" completed."
    echo
else
    echo
    echo "Clone failed."
    echo "  Common reasons include:"
    echo "    - You've misspelled the repo"
    echo "    - Repo doesn't exist"
    echo "    - GitHub may be down (unlikely)"
    echo "    - Note: If it asks for a Username and Password for https://github.com,"
    echo "            it means the Repository is private or doesn't exist."
    echo "            Git doesn't check whether a repo exists or not before asking,"
    echo "            It just does assumes it's private."
    echo "            Also, username and password are no longer supported for clone."
    echo
    exit 1
fi
