#!/usr/bin/env bash

set -e

# Ensure $HOME exists
if [ -z "$HOME" ]; then
    echo "HOME variable not set!"
    exit 1
fi

SSH_DIR="$HOME/.ssh"
BACKUP_DIR="$HOME/.ssh.bak"

mkdir -p "$BACKUP_DIR"

echo "Disabling SSH..."

[ -f "$SSH_DIR/id_ed25519" ] && mv -f "$SSH_DIR/id_ed25519" "$BACKUP_DIR/"
[ -f "$SSH_DIR/id_ed25519.pub" ] && mv -f "$SSH_DIR/id_ed25519.pub" "$BACKUP_DIR/"

ssh-add -D || true

echo "SSH disabled."

# Hang

KEEP_OPEN=true

if [ "$KEEP_OPEN" = true ]; then
    echo
    read -p "Press 'Enter' to exit / Type 'disable' to disable hanging: " response
    if [ "$response" = "disable" ]; then
        sed -i 's/^KEEP_OPEN=true/KEEP_OPEN=false/' "$0"
        echo
        echo "KEEP_OPEN set to false"
        echo "Change 'KEEP_OPEN=true' to enable"
        sleep 4
    fi
fi
