#!/usr/bin/env bash

set -e

DEFAULT_EXCLUDE="# git ls-files --others --exclude-from=.git/info/exclude
# Lines that start with '#' are comments.
# For a project mostly in C, the following would be a good set of
# exclude patterns (uncomment them if you want to use them):
# *.[oa]
# *~"

all_replaced=true

for f in */.git/info/exclude; do
  if [[ -f "$f" ]]; then
    echo "$DEFAULT_EXCLUDE" > "$f"

    if [[ ! -s "$f" ]]; then
      echo "Warning: $f is empty after writing default content!"
      all_replaced=false
    fi
  fi
done

if $all_replaced; then
  echo "All exclude files replaced with default content successfully."
fi

# Hang

KEEP_OPEN=true

if [ "$KEEP_OPEN" = true ]; then
    echo
    read -p "Press 'Enter' to exit / Type 'disable' to disable hanging: " response
    if [ "$response" = "disable" ]; then
        sed -i 's/^KEEP_OPEN=true/KEEP_OPEN=false/' "$0"
        echo
        echo "KEEP_OPEN set to false"
        echo "Change 'KEEP_OPEN=true' to enable"
        sleep 4
    fi
fi
