#!/usr/bin/env bash
set -e

git add .

# Prompt the user for a commit message
read -rp "Enter commit message: " commit_message

# If the message is empty, use "auto-commit"
if [ -z "$commit_message" ]; then
    commit_message="auto-commit"
fi

git commit -m "$commit_message"
git push
