#!/usr/bin/env bash

set -e

read -rp "Enter commit message (Enter to use 'auto-commit'): " commit_message

if [ -z "$commit_message" ]; then
    commit_message="auto-commit"
fi

git add .
git commit -m "$commit_message"
git push

# Hang

KEEP_OPEN=true

if [ "$KEEP_OPEN" = true ]; then
    echo
    read -p "Press 'Enter' to exit / Type 'disable' to disable hanging: " response
    if [ "$response" = "disable" ]; then
        sed -i 's/^KEEP_OPEN=true/KEEP_OPEN=false/' "$0"
        echo
        echo "KEEP_OPEN set to false"
        echo "Change 'KEEP_OPEN=true' to enable"
        sleep 4
    fi
fi
