#!/usr/bin/env bash

set -e

# Get the current folder name
current_dir=$(basename "$PWD")

# Determine what to add based on folder
if [ "$current_dir" = "automation" ]; then
    echo "Detected 'automation/' folder. Adding parent repo files..."
    git add ..
else
    echo "Adding current folder files..."
    git add .
fi

# Show status
git status

# Hang

KEEP_OPEN=true

if [ "$KEEP_OPEN" = true ]; then
    echo
    read -p "Press 'Enter' to exit / Type 'disable' to disable hanging: " response
    if [ "$response" = "disable" ]; then
        sed -i 's/^KEEP_OPEN=true/KEEP_OPEN=false/' "$0"
        echo
        echo "KEEP_OPEN set to false"
        echo "Change 'KEEP_OPEN=true' to enable"
        sleep 4
    fi
fi
